spring.datasource.url=jdbc:mysql://localhost:3306/shopapi
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.user.password=password

server.port=8080

jwt.secret=${JWT_SECRETKEY}
jwt.expiration=86400000
#token expires in 24 hrs

#application.properties
#The settings file. Tells Spring Boot where MySQL lives, your credentials, and how to behave. Without this, Spring Boot doesn't know a database exists.
#Spring Boot ? reads this file on startup ? connects to MySQL